# Default values for the chatbot kubernetes application

# Declare the values for the variables for the given template files


# This defines all the variables for the update-bot
# UPDATE-BOT NEEDS TO BE UPDATED WHEN PR HAS BEEN MERGED
bot:
  secret:
    caicredentialsurl: <url>
    caicredentialsid: <id>
    caicredentialssecret: <secret>
    boturl: <bot-url>
    caixtoken: <token>
    stackurl: <url>
    stacktag: <tag>
    stackkey: <key>
    dbname: <name>
    dbhost: <host>
    dbusername: <name>
    dbpassword: <password>
  updatebot:
    cronjob: <cronjob>
    job: <job>
  botobservertool:
    apirule:
      gateway: <gateway>
      port: 3000
    deployment:
      image: <image-name>
      containerport: 3000
    service:
      port: 3000
      targetport: 3000


# This defines all the variables for the api-mssql-function
apimssqlfunction:
  deployment:
    env:
      database: <databasename>
      host: <hostname>
      username: <username>
      password: <password>
      reference: <referenceinrepo>
      basedir: <basedir>


# This defines all the variables for the database-mssql
databasemssql:
  deployment:
    image: lasseurban/bot-db
  secret:
    username: <username>
    password: <password>

# This defines all the variables for the alert notification
alertnotification:
  email: <email>
  secret:
    anregion: <anregion>
    clusterdomain: <clusterdomain>
