apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: mssql
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: bot-observer
    meta.helm.sh/release-namespace: karl-kyma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mssql
          image: lasseurban/bot-db    #change it to your image
          imagePullPolicy: Always
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: password
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: mssql
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: bot-observer
    meta.helm.sh/release-namespace: karl-kyma
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
