kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  labels:
    app: mssql
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: bot-observer
    meta.helm.sh/release-namespace: karl-kyma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
