apiVersion: v1
kind: Secret
metadata:
  name: mssql
  labels:
    app: api-mssql-db
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: bot-observer
    meta.helm.sh/release-namespace: karl-kyma
type: Opaque
data:
  username: c2E=
  password: bWZyQ1BUSzM=
