apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-bot-job
spec:
  # Update intervall for new questions and answers
  schedule: "*/30 * * * *"     #change it to your schedule
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: update-bot-container
            image: {{ .Values.bot.updatebot.cronjob.update.image }}:{{ .Values.bot.updatebot.cronjob.update.tag }}
            imagePullPolicy: Always
            env:
              - name: CAI_CREDENTIALS_URL
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: cai-credentials-url
              - name: CAI_CREDENTIALS_ID
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: cai-credentials-id
              - name: CAI_CREDENTIALS_SECRET
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: cai-credentials-secret
              - name: BOT_URL
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: bot-url
              - name: X_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: cai-x-token
              - name: STACK_URL
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: stack-url
              - name: STACK_TAG
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: stack-tag
              - name: STACK_KEY
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: stack-key
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: db-name
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: db-host
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: db-username
              - name: DB_PW
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: db-password
              - name: UPDATE_ALL
                value: "N"
          imagePullSecrets:
          - name: regcred
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-all-bot-job
spec:
  # update intervall for refreshing all questions
  schedule: "15 23 * * *"     #change it to your schedule
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: update-bot-container
            image: {{ .Values.bot.updatebot.cronjob.updateall.image }}:{{ .Values.bot.updatebot.cronjob.updateall.tag }}
            imagePullPolicy: Always
            env:
              - name: CAI_CREDENTIALS_URL
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: cai-credentials-url
              - name: CAI_CREDENTIALS_ID
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: cai-credentials-id
              - name: CAI_CREDENTIALS_SECRET
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: cai-credentials-secret
              - name: BOT_URL
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: bot-url
              - name: X_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: cai-x-token
              - name: STACK_URL
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: stack-url
              - name: STACK_TAG
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: stack-tag
              - name: STACK_KEY
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: stack-key
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: db-name
              - name: DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: db-host
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: db-username
              - name: DB_PW
                valueFrom:
                  secretKeyRef:
                    name: bot-secret
                    key: db-password
              - name: UPDATE_ALL
                value: "Y"
          imagePullSecrets:
          - name: regcred

