kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  labels:
    app: mssql
spec:
  volumeName: {{ .Values.databasemssql.pvc.volumename }}
  storageClassName: {{ .Values.databasemssql.pvc.storageclassname }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
