kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  labels:
    app: mssql
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
