apiVersion: v1
kind: Secret
metadata:
  name: mssql
  labels:
    app: api-mssql-db
type: Opaque
data:
  username: {{ .Values.databasemssql.secret.username}}
  password: {{ .Values.databasemssql.secret.password}}
